// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskyRevamp.Infrastructure;

#nullable disable

namespace TaskyRevamp.Infrastructure.Migrations
{
    [DbContext(typeof(EfDbContext))]
    [Migration("20250921142107_add-Source-table")]
    partial class addSourcetable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TaskyRevamp.Domain.Models.SystemConfiguration.DefaultViewSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DefaultSelected")
                        .HasColumnType("int");

                    b.Property<int>("SubTaskLevels")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DefaultViewSettings");
                });

            modelBuilder.Entity("TaskyRevamp.Domain.Models.SystemConfiguration.PrioritySettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BackgroundColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameArabic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameEnglish")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PrioritySettings");
                });

            modelBuilder.Entity("TaskyRevamp.Domain.Models.SystemConfiguration.RecycleBinSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("CustomDays")
                        .HasColumnType("int");

                    b.Property<int>("PeriodType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RecycleBinSettings");
                });

            modelBuilder.Entity("TaskyRevamp.Domain.Models.SystemConfiguration.RejectionSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("CustomDays")
                        .HasColumnType("int");

                    b.Property<int>("PeriodType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RejectionSettings");
                });

            modelBuilder.Entity("TaskyRevamp.Domain.Models.SystemConfiguration.Source", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DescriptionArabic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionEnglish")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("NameArabic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameEnglish")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UpdatedById")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("UpdatedById");

                    b.ToTable("Source");
                });

            modelBuilder.Entity("TaskyRevamp.Domain.Models.SystemConfiguration.StatusSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BackgroundColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameArabic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameEnglish")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StatusSettings");
                });

            modelBuilder.Entity("TaskyRevamp.Domain.Models.SystemConfiguration.ViewTaskSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("ViewType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ViewTaskSettings");
                });

            modelBuilder.Entity("TaskyRevamp.Domain.Models.SystemConfiguration.WeeklyReportSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Day")
                        .HasColumnType("int");

                    b.Property<int>("Language")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("Time")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("WeeklyReportSettings");
                });

            modelBuilder.Entity("TaskyRevamp.Domain.Models.SystemConfiguration.WorkingDaysSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Day")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("WorkingDaysSettings");
                });

            modelBuilder.Entity("TaskyRevamp.Domain.Models.Task.Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("TaskAttachmentsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UploadedById")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TaskAttachmentsId");

                    b.HasIndex("UploadedById");

                    b.ToTable("Attachment");
                });

            modelBuilder.Entity("TaskyRevamp.Domain.Models.Task.ChangeEndDateRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("NewEndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RequesterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TaskItemId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RequesterId");

                    b.HasIndex("TaskId");

                    b.HasIndex("TaskItemId");

                    b.ToTable("ChangeEndDateRequest");
                });

            modelBuilder.Entity("TaskyRevamp.Domain.Models.Task.ChecklistItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("TaskChecklistId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("TaskChecklistId");

                    b.ToTable("ChecklistItem");
                });

            modelBuilder.Entity("TaskyRevamp.Domain.Models.Task.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("TaskCommentsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("TaskCommentsId");

                    b.ToTable("Comment");
                });

            modelBuilder.Entity("TaskyRevamp.Domain.Models.Task.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("TaskAssigneesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TaskItemId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TaskAssigneesId");

                    b.HasIndex("TaskItemId");

                    b.ToTable("Department");
                });

            modelBuilder.Entity("TaskyRevamp.Domain.Models.Task.TaskAssignees", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TaskItemId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TaskItemId");

                    b.ToTable("TaskAssignees");
                });

            modelBuilder.Entity("TaskyRevamp.Domain.Models.Task.TaskAttachments", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("TaskAttachments");
                });

            modelBuilder.Entity("TaskyRevamp.Domain.Models.Task.TaskChecklist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("TaskChecklist");
                });

            modelBuilder.Entity("TaskyRevamp.Domain.Models.Task.TaskComments", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("TaskComments");
                });

            modelBuilder.Entity("TaskyRevamp.Domain.Models.Task.TaskDependencies", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("TaskDependencies");
                });

            modelBuilder.Entity("TaskyRevamp.Domain.Models.Task.TaskEscalation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EscalatedToId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RequestedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TaskItemId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EscalatedToId");

                    b.HasIndex("RequestedById");

                    b.HasIndex("TaskId");

                    b.HasIndex("TaskItemId");

                    b.ToTable("TaskEscalation");
                });

            modelBuilder.Entity("TaskyRevamp.Domain.Models.Task.TaskHistoryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TaskItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ById");

                    b.HasIndex("TaskId");

                    b.HasIndex("TaskItemId");

                    b.ToTable("TaskHistoryEntry");
                });

            modelBuilder.Entity("TaskyRevamp.Domain.Models.Task.TaskItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.PrimitiveCollection<string>("AssignedDepartmentIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("AssignedIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("AttachmentsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChecklistId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CommentsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DependenciesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DescriptionArabic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionEnglish")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TitleArabic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleEnglish")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UpdateddById")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AttachmentsId");

                    b.HasIndex("ChecklistId");

                    b.HasIndex("CommentsId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("CreatorId");

                    b.HasIndex("DependenciesId");

                    b.HasIndex("ParentId");

                    b.HasIndex("SourceId");

                    b.HasIndex("TypeId");

                    b.HasIndex("UpdateddById");

                    b.ToTable("TaskItem");
                });

            modelBuilder.Entity("TaskyRevamp.Domain.Models.Task.TaskSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TaskSource");
                });

            modelBuilder.Entity("TaskyRevamp.Domain.Models.Task.TaskType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TaskType");
                });

            modelBuilder.Entity("TaskyRevamp.Domain.Models.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DistinguishedName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GivenName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsManager")
                        .HasColumnType("bit");

                    b.Property<string>("Mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameArabic")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameEnglish")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("TaskAssigneesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("TaskAssigneesId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TaskyRevamp.Domain.Models.Users.UserDelegations.UserDelegation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FromDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FromUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ToDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ToUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UpdateddById")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("UpdateddById");

                    b.ToTable("UserDelegation");
                });

            modelBuilder.Entity("TaskyRevamp.Domain.Models.SystemConfiguration.Source", b =>
                {
                    b.HasOne("TaskyRevamp.Domain.Models.Users.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TaskyRevamp.Domain.Models.Users.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("TaskyRevamp.Domain.Models.Task.Attachment", b =>
                {
                    b.HasOne("TaskyRevamp.Domain.Models.Task.TaskAttachments", null)
                        .WithMany("Items")
                        .HasForeignKey("TaskAttachmentsId");

                    b.HasOne("TaskyRevamp.Domain.Models.Users.User", "UploadedBy")
                        .WithMany()
                        .HasForeignKey("UploadedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UploadedBy");
                });

            modelBuilder.Entity("TaskyRevamp.Domain.Models.Task.ChangeEndDateRequest", b =>
                {
                    b.HasOne("TaskyRevamp.Domain.Models.Users.User", "Requester")
                        .WithMany()
                        .HasForeignKey("RequesterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TaskyRevamp.Domain.Models.Task.TaskItem", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskyRevamp.Domain.Models.Task.TaskItem", null)
                        .WithMany("ChangeRequests")
                        .HasForeignKey("TaskItemId");

                    b.Navigation("Requester");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("TaskyRevamp.Domain.Models.Task.ChecklistItem", b =>
                {
                    b.HasOne("TaskyRevamp.Domain.Models.Users.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TaskyRevamp.Domain.Models.Task.TaskChecklist", null)
                        .WithMany("Items")
                        .HasForeignKey("TaskChecklistId");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("TaskyRevamp.Domain.Models.Task.Comment", b =>
                {
                    b.HasOne("TaskyRevamp.Domain.Models.Users.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TaskyRevamp.Domain.Models.Task.TaskComments", null)
                        .WithMany("Items")
                        .HasForeignKey("TaskCommentsId");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("TaskyRevamp.Domain.Models.Task.Department", b =>
                {
                    b.HasOne("TaskyRevamp.Domain.Models.Task.TaskAssignees", null)
                        .WithMany("Departments")
                        .HasForeignKey("TaskAssigneesId");

                    b.HasOne("TaskyRevamp.Domain.Models.Task.TaskItem", null)
                        .WithMany("AssignedDepartments")
                        .HasForeignKey("TaskItemId");
                });

            modelBuilder.Entity("TaskyRevamp.Domain.Models.Task.TaskAssignees", b =>
                {
                    b.HasOne("TaskyRevamp.Domain.Models.Task.TaskItem", null)
                        .WithMany("Assignees")
                        .HasForeignKey("TaskItemId");
                });

            modelBuilder.Entity("TaskyRevamp.Domain.Models.Task.TaskEscalation", b =>
                {
                    b.HasOne("TaskyRevamp.Domain.Models.Users.User", "EscalatedTo")
                        .WithMany()
                        .HasForeignKey("EscalatedToId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TaskyRevamp.Domain.Models.Users.User", "RequestedBy")
                        .WithMany()
                        .HasForeignKey("RequestedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TaskyRevamp.Domain.Models.Task.TaskItem", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskyRevamp.Domain.Models.Task.TaskItem", null)
                        .WithMany("Escalations")
                        .HasForeignKey("TaskItemId");

                    b.Navigation("EscalatedTo");

                    b.Navigation("RequestedBy");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("TaskyRevamp.Domain.Models.Task.TaskHistoryEntry", b =>
                {
                    b.HasOne("TaskyRevamp.Domain.Models.Users.User", "By")
                        .WithMany()
                        .HasForeignKey("ById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TaskyRevamp.Domain.Models.Task.TaskItem", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskyRevamp.Domain.Models.Task.TaskItem", null)
                        .WithMany("History")
                        .HasForeignKey("TaskItemId");

                    b.Navigation("By");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("TaskyRevamp.Domain.Models.Task.TaskItem", b =>
                {
                    b.HasOne("TaskyRevamp.Domain.Models.Task.TaskAttachments", "Attachments")
                        .WithMany()
                        .HasForeignKey("AttachmentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskyRevamp.Domain.Models.Task.TaskChecklist", "Checklist")
                        .WithMany()
                        .HasForeignKey("ChecklistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskyRevamp.Domain.Models.Task.TaskComments", "Comments")
                        .WithMany()
                        .HasForeignKey("CommentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskyRevamp.Domain.Models.Users.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TaskyRevamp.Domain.Models.Users.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TaskyRevamp.Domain.Models.Task.TaskDependencies", "Dependencies")
                        .WithMany("Items")
                        .HasForeignKey("DependenciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskyRevamp.Domain.Models.Task.TaskItem", "Parent")
                        .WithMany("Subtasks")
                        .HasForeignKey("ParentId");

                    b.HasOne("TaskyRevamp.Domain.Models.Task.TaskSource", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskyRevamp.Domain.Models.Task.TaskType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskyRevamp.Domain.Models.Users.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdateddById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("TaskyRevamp.Domain.Models.Task.Progress", "ActualProgress", b1 =>
                        {
                            b1.Property<Guid>("TaskItemId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("TaskItemId");

                            b1.ToTable("TaskItem");

                            b1.WithOwner()
                                .HasForeignKey("TaskItemId");
                        });

                    b.OwnsOne("TaskyRevamp.Domain.Models.Task.Reminder", "Reminder", b1 =>
                        {
                            b1.Property<Guid>("TaskItemId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("TaskItemId");

                            b1.ToTable("TaskItem");

                            b1.WithOwner()
                                .HasForeignKey("TaskItemId");
                        });

                    b.OwnsOne("TaskyRevamp.Domain.Models.Task.Weight", "ActualWeight", b1 =>
                        {
                            b1.Property<Guid>("TaskItemId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("TaskItemId");

                            b1.ToTable("TaskItem");

                            b1.WithOwner()
                                .HasForeignKey("TaskItemId");
                        });

                    b.OwnsOne("TaskyRevamp.Domain.Models.Task.Weight", "PlannedWeight", b1 =>
                        {
                            b1.Property<Guid>("TaskItemId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("TaskItemId");

                            b1.ToTable("TaskItem");

                            b1.WithOwner()
                                .HasForeignKey("TaskItemId");
                        });

                    b.Navigation("ActualProgress")
                        .IsRequired();

                    b.Navigation("ActualWeight")
                        .IsRequired();

                    b.Navigation("Attachments");

                    b.Navigation("Checklist");

                    b.Navigation("Comments");

                    b.Navigation("CreatedBy");

                    b.Navigation("Creator");

                    b.Navigation("Dependencies");

                    b.Navigation("Parent");

                    b.Navigation("PlannedWeight")
                        .IsRequired();

                    b.Navigation("Reminder");

                    b.Navigation("Source");

                    b.Navigation("Type");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("TaskyRevamp.Domain.Models.Users.User", b =>
                {
                    b.HasOne("TaskyRevamp.Domain.Models.Task.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId");

                    b.HasOne("TaskyRevamp.Domain.Models.Task.TaskAssignees", null)
                        .WithMany("Items")
                        .HasForeignKey("TaskAssigneesId");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("TaskyRevamp.Domain.Models.Users.UserDelegations.UserDelegation", b =>
                {
                    b.HasOne("TaskyRevamp.Domain.Models.Users.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TaskyRevamp.Domain.Models.Users.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdateddById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedBy");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("TaskyRevamp.Domain.Models.Task.TaskAssignees", b =>
                {
                    b.Navigation("Departments");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("TaskyRevamp.Domain.Models.Task.TaskAttachments", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("TaskyRevamp.Domain.Models.Task.TaskChecklist", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("TaskyRevamp.Domain.Models.Task.TaskComments", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("TaskyRevamp.Domain.Models.Task.TaskDependencies", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("TaskyRevamp.Domain.Models.Task.TaskItem", b =>
                {
                    b.Navigation("AssignedDepartments");

                    b.Navigation("Assignees");

                    b.Navigation("ChangeRequests");

                    b.Navigation("Escalations");

                    b.Navigation("History");

                    b.Navigation("Subtasks");
                });
#pragma warning restore 612, 618
        }
    }
}
