<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<Compile Remove="Permission\GeneralModule\Command\**" />
		<EmbeddedResource Remove="Permission\GeneralModule\Command\**" />
		<None Remove="Permission\GeneralModule\Command\**" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Hangfire.Core" Version="1.8.20" />
		<PackageReference Include="MediatR" Version="13.0.0" />
		<PackageReference Include="Microsoft.AspNetCore.Http" Version="2.3.0" />
		<PackageReference Include="Microsoft.Extensions.Localization" Version="9.0.8" />
		<PackageReference Include="System.DirectoryServices" Version="9.0.8" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.13.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\TaskyRevamp.Domain\TaskyRevamp.Domain.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Account\Query\" />
		<Folder Include="Permission\GeneralModulePrivilege\Command\" />
		<Folder Include="SystemConfiguration\RecycleBinSettings\Command\" />
	</ItemGroup>

</Project>
