<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<NoDefaultLaunchSettingsFile>true</NoDefaultLaunchSettingsFile>
		<StaticWebAssetProjectMode>Default</StaticWebAssetProjectMode>
		<BlazorWebAssemblyLoadAllGlobalizationData>true</BlazorWebAssemblyLoadAllGlobalizationData>
	</PropertyGroup>

	<ItemGroup>
		<Compile Remove="Pages\NewFolder\**" />
		<Compile Remove="Pages\Task\TaskDetails\**" />
		<Content Remove="Pages\NewFolder\**" />
		<Content Remove="Pages\Task\TaskDetails\**" />
		<EmbeddedResource Remove="Pages\NewFolder\**" />
		<EmbeddedResource Remove="Pages\Task\TaskDetails\**" />
		<None Remove="Pages\NewFolder\**" />
	  <Compile Remove="Consumer\css\**" />
	  <Compile Remove="Pages\NewFolder\**" />
	  <Content Remove="Consumer\css\**" />
	  <Content Remove="Pages\NewFolder\**" />
	  <EmbeddedResource Remove="Consumer\css\**" />
	  <EmbeddedResource Remove="Pages\NewFolder\**" />
	  <None Remove="Consumer\css\**" />
	  <None Remove="Pages\NewFolder\**" />
	  <None Remove="Pages\Task\TaskDetails\**" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Blazored.LocalStorage" Version="4.5.0" />
		<PackageReference Include="MailKit" Version="4.14.1" />
		<PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="10.0.0" />
		<PackageReference Include="Microsoft.Identity.Client" Version="4.79.2" />
		<PackageReference Include="MimeKit" Version="4.14.0" />
		<PackageReference Include="EPPlus" Version="8.1.0" />
		<PackageReference Include="Stingray.Components.MultiSelectComponent" Version="1.0.37" />

		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="9.0.7" />
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Authentication" Version="9.0.7" />

		<PackageReference Include="Microsoft.AspNetCore.Localization" Version="2.3.0" />
		<PackageReference Include="Microsoft.Extensions.Localization" Version="9.0.8" />
		<PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="9.0.8" />

		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
		<PackageReference Include="DocumentFormat.OpenXml" Version="2.21.0" />

		<PackageReference Include="Syncfusion.Blazor.Calendars" Version="31.1.21" />
		<PackageReference Include="Syncfusion.Blazor.RichTextEditor" Version="31.1.21" />
		<PackageReference Include="Syncfusion.Blazor.Themes" Version="31.1.21" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.13.0" />

	</ItemGroup>
	<ItemGroup>
		<Compile Update="SyncfusionLocalization\SfResources.Designer.cs">
			<DependentUpon>SfResources.resx</DependentUpon>
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\TaskyRevamp.Dto\TaskyRevamp.Dto.csproj" />
	</ItemGroup>
	<ItemGroup>
		<EmbeddedResource Update="SyncfusionLocalization\SfResources.resx">
			<LastGenOutput>SfResources.Designer.cs</LastGenOutput>
			<Generator>PublicResXFileCodeGenerator</Generator>
		</EmbeddedResource>
	</ItemGroup>

</Project>
